name: Deploy API

on:
  workflow_dispatch:
  release:
    types: [published]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Restore Dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build src/API -c Release -o bin
      - name: Copy Scripts
        run: cp scripts/* bin/
      - name: Install SSH keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
      - name: Deploy API
        run: rsync -rlgoDzvc bin/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.OUTPUT_DIR }}
      - name: Restart Service
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "systemctl restart api.service && exit" 
      - name: Cleanup SSH
        run: rm -rf ~/.ssh
